version: '3'
services:
  backend:
    restart: always
    build: .
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db

  queue:
    restart: always
    build: .
    env_file:
      - .env
    command: python consumer.py
    depends_on:
      - db


  db:
    container_name: db
    restart: always
    image: postgres:latest
    ports:
      - "54322:5432"
    env_file:
      - .env
    volumes:
      - .dbdata:/var/lib/postgresql/data